trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  Major-Minor: 4.1
  Revision: $[ counter(variables['Major-Minor'],0) ]
  BuildConfiguration: 'Release'

name: $(Major-Minor).$(Revision)

steps:
- checkout: self
  submodules: 'true'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100-rc.2.23502.2'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: byBuildNumber
    arguments: '--configuration $(BuildConfiguration) -p:Version=$(Build.BuildNumber);FileVersion=$(Build.BuildNumber)'

- task: codesigning@2
  inputs:
    secureFileId: 'ootd.pfx'
    signCertPassword: $(pfx_password)
    files: 'OotD.Launcher\bin\Release\net8.0-windows7.0\OotD.*(dll|exe)'
    timeServer: 'http://timestamp.digicert.com'
    hashingAlgorithm: 'SHA256'
    signToolLocationMethod: 'latest'

- task: CmdLine@2
  inputs:
    script: 'iscc /Q "Setup Script.iss"'

- task: codesigning@2
  inputs:
    secureFileId: 'ootd.pfx'
    signCertPassword: $(pfx_password)
    files: 'serverStaging/*.exe'
    timeServer: 'http://timestamp.digicert.com'
    hashingAlgorithm: 'SHA256'
    signToolLocationMethod: 'latest'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'ServerStaging'
    ArtifactName: 'artifact'
    publishLocation: 'Container'